#!/bin/bash

HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."
pwd
ls -alt

cat "../versions.txt" | while read capsulecd_line
do
    cat "$HOOKS_DIR/versions.txt" | while read language_line
    do
        # split the language line into its two components, the version string to be used in the tag, and the actual docker base image.
        IFS=\  read tag_version base_image <<<"$language_line"
        IMAGE_TAG="${DOCKER_REPO}:${capsulecd_line}-${DOCKER_TAG}"

        if [ "${tag_version}" != "latest" ]; then
            IMAGE_TAG="${IMAGE_TAG}${tag_version}"
        fi

        echo "docker build -f $DOCKERFILE_PATH --build-arg base_image=${base_image} --build-arg capsulecd_version=${capsulecd_line} -t ${IMAGE_TAG} ."
        docker build -f $DOCKERFILE_PATH --build-arg base_image=${base_image} --build-arg capsulecd_version=${capsulecd_line} -t ${IMAGE_TAG} .
    done
done


