#!/bin/bash

# original docker push command
echo "docker push $IMAGE_NAME"

cat "versions.txt" | while read capsulecd_line
do
    cat "$DOCKER_TAG/versions.txt" | while read language_line
    do
        # split the language line into its two components, the version string to be used in the tag, and the actual docker base image.
        IFS=\  read tag_version base_image <<<"$language_line"
        IMAGE_TAG="${DOCKER_REPO}:${capsulecd_line}-${DOCKER_TAG}"

        if [ "${tag_version}" != "latest" ]; then
            IMAGE_TAG="${IMAGE_TAG}${tag_version}"
        fi

        echo "docker push ${IMAGE_TAG}"
        docker push ${IMAGE_TAG}
    done
done
